### ISSUE TITLE
AiCameraGetLocalData entry missing from \shaders\zoic.dll file

### ISSUE THREAD

**Issue by baksagram** [zpelgrims/zoic#18]
Using Windows, Cinema 4D r17 and r18 with Arnold 5. I have just bought it and it won't work. I hope it is the right way to ask for help. Thank you.

**Comment by zpelgrims** [comment]
Hey man, the shader hasn't been updated for Arnold 5 yet. There have been some major API changes so it won't work. I'm in the process of updating it, but I don't know when I will finish with it.

I'll reimburse you for it, ofcourse!

**Comment by zpelgrims** [comment]
I've just refunded, hang on a while for the Arnold 5 version!

**Comment by baksagram** [comment]
Hey, that is very kind of you, thanks for the help and the quick reply! If I decide to try it on a previous version of Arnold, I'll be sure to buy it again.
